[versions]
agp = "9.0.0"
kotlin = "2.2.10"
coreKtx = "1.10.1"
junit = "4.13.2"
junitVersion = "1.2.1"
junit4 = "1.7.8"
espressoCore = "3.6.1"
lifecycleRuntimeKtx = "2.6.1"
lifecycleViewmodelCompose = "2.6.1"
activityCompose = "1.8.0"
composeBom = "2024.04.01"
generativeai = "0.2.2"
googleAndroidLibrariesMapsplatformSecretsGradlePlugin = "2.0.1"
googleServices = "4.4.2"
firebase-bom = "33.6.0"
material = "1.3.1"
materialIcons = "1.7.5"
timber = "5.0.1"
gsm-base = "18.5.0"
nav_version = "2.8.4"
gson = "2.10.1"
accompanist = "0.36.0"
roomCommon = "2.6.1"
swiperefreshlayout = "1.7.6"
paging = "3.2.1"
csv = "2.15.0"
treessecene = "1.1.2"
coroutinesPlayServices = "1.10.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase-bom" }
firebase-auth-ktx = { module = "com.google.firebase:firebase-auth-ktx" }
firebase-analytics-ktx = { module = "com.google.firebase:firebase-analytics-ktx" }
firebase-firestore-ktx = { module = "com.google.firebase:firebase-firestore-ktx"}
play-services-base = { group = "com.google.android.gms",name="play-services-base",version.ref="gsm-base"}
coroutines-play-services = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-play-services", version.ref = "coroutinesPlayServices" }

junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4",version.ref ="junit4" }

androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycleViewmodelCompose" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3",version.ref = "material" }
navigation-compose = { group = "androidx.navigation",name="navigation-compose",version.ref="nav_version"}
navigation-animation = { group = "com.google.accompanist",name="accompanist-navigation-animation",version.ref="accompanist"}
accompanist = { group = "com.google.accompanist", name = "accompanist-systemuicontroller", version.ref = "accompanist" }
generativeai = { group = "com.google.ai.client.generativeai", name = "generativeai", version.ref = "generativeai" }
icons = { group = "androidx.compose.material", name = "material-icons-extended", version.ref = "materialIcons" }
timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
androidx-room-common = { group = "androidx.room", name = "room-common", version.ref = "roomCommon" }
swiperefreshlayout = {group="androidx.compose.foundation",name="foundation",version.ref="swiperefreshlayout"}
androidx-paging = { group = "androidx.paging", name = "paging-compose", version.ref = "paging" }
csv = {group="com.fasterxml.jackson.dataformat",name="jackson-dataformat-csv",version.ref="csv"}
treessence= {group="com.github.bastienpaulfr",name="Treessence",version.ref="treessecene"}

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
google-android-libraries-mapsplatform-secrets-gradle-plugin = { id = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin", version.ref = "googleAndroidLibrariesMapsplatformSecretsGradlePlugin" }
google-services = {id="com.google.gms.google-services",version.ref ="googleServices"}
